# Generated by Django 4.1.1 on 2022-11-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_product_description_en_product_description_tr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_uz',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_uz',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name_uz',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_tr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_tr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_tr',
        ),
    ]
