# Generated by Django 4.1.1 on 2022-11-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_name_uz_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='cartobject',
            name='confirm',
            field=models.BooleanField(default=True),
        ),
    ]
