# Generated by Django 4.1.1 on 2022-11-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tsop_list',
            field=models.BooleanField(default=False),
        ),
    ]
