# Generated by Django 4.1.1 on 2022-11-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_product_tsop_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tsop_list',
            new_name='stop_list',
        ),
    ]
