# Generated by Django 4.1.1 on 2022-11-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='check_phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
